feat: Adds first draft of slurm-cluster setup tutorial
UNIVERSE-HPC/course-material pull request #100
Opened 2024-04-30 11:24 UTC by jackleland

Adds a first draft of a tutorial to set up a training slurm cluster on aws, based on the Flight Solo image and SPack. 

I added it as a single section on a separate course into the HPC theme but, given it's not training material, we may want to put it elsewhere - perhaps a new 'administrative material' theme. That or we would need to incorporate a change into gutenberg which hides certain sections/courses/themes depending on whether the account is a trainee or a trainer, but that's would not be a change made to this repo. 

Addresses #99.

2024-05-03 10:46 UTC, martinjrobins requested changes
great stuff, thanks @jackleland! couple of minor changes about replacing tabs with spaces below

2024-05-10 09:35 UTC, jackleland commented on high_performance_computing/hpc_aws_slurm_setup/01_flight_solo_setup.md
> +	      all: '{name}/{version}'
Addressed in [e5320b3](https://github.com/UNIVERSE-HPC/course-material/pull/100/commits/e5320b33b06895ebe27b8c527340782ba4997517)

2024-05-10 09:35 UTC, jackleland commented on high_performance_computing/hpc_aws_slurm_setup/01_flight_solo_setup.md
> +		  SHAREPUBKEY=true
Addressed in [e5320b3](https://github.com/UNIVERSE-HPC/course-material/pull/100/commits/e5320b33b06895ebe27b8c527340782ba4997517), also found one before `content` on the line above.

2024-05-10 09:48 UTC, martinjrobins approved these changes
thanks @jackleland, happy to merge

2024-05-10 09:48 UTC, merged