Piloted and revised Foundational HPC course
UNIVERSE-HPC/course-material pull request #187
Opened 2024-12-05 11:33 UTC by steve-crouch

A piloted and revised Foundational HPC course based on material from EPCC's Intro to HPC course, comprised of 4 modules.

2025-01-16 12:27 UTC, martinjrobins commented
Thanks @steve-crouch, I can see those link errors arn't coming from your changes, so happy to ignore these! I'll try to get a review done asap

2025-01-17 15:26 UTC, alasdairwilson reviewed
I am reviewing this in detail but I initially had just a general thought on the layout, I think the high performance computing theme is organised incorrectly. 

The "Theme" page has too much specificity in it, take for comparison the technology and tooling theme where one course is on say "IDEs" and another on "Testing" to the HPC theme where one course is on "Parallel Computing" and another is on "Introduction to parallelism" and another on "Introduction to supercomputing". I know this is not all added in this PR though.


![image](https://github.com/user-attachments/assets/aeb708cd-40c8-445b-92e1-b1e22b3e305e)
![image](https://github.com/user-attachments/assets/ef0fed8d-9843-480d-9f67-525191492432)

There would still need to be work to do to get the rest of the Theme in line and these 4 "streams" could be linked together in the theme diagram too which would not be represented in the default gridbox layout.

2025-01-28 21:04 UTC, alasdairwilson commented on high_performance_computing/computer_simulations/01_intro.md
> +- allow the wolf population to die out
```suggestion
To understand the importance of choosing the right input parameters, and see the difference even the smallest variation can produce, you are encouraged to play with the values of different parameters.
Try to find values of parameters that:

- Allow both populations to be stable (i.e. neither population is dying out) even after 1000 time steps.
- Allow the sheep population to die out.
- Allow the wolf population to die out.
```

2025-01-28 21:04 UTC, alasdairwilson commented on high_performance_computing/computer_simulations/01_intro.md
> +How difficult was it to find the sets of parameters to meet the conditions? Have you noticed anything unexpected?
```suggestion
:::callout{variant="discussion}
How difficult was it to find the sets of parameters to meet the conditions? Have you noticed anything unexpected?
:::
```

2025-01-28 21:05 UTC, alasdairwilson commented on high_performance_computing/computer_simulations/01_intro.md
> +3) the computer and information infrastructure e.g. hardware, networking and data management components.
```suggestion
1. algorithms and models
1. software developed to solve problems and
1. the computer and information infrastructure e.g. hardware, networking and data management components.
```

2025-01-28 21:14 UTC, alasdairwilson commented on high_performance_computing/computer_simulations/01_intro.md
> +However, more recently, other disciplines, such as medicine (e.g. medical imaging, blood flow simulations, bone structure simulations), biology (e.g. ecosystem and environmental modelling) and econom
```suggestion
Some of the disciplines traditionally associated with computational science include: atmospheric sciences (e.g. weather forecasting, climate and ocean modelling, seismology etc.), astrophysics, nuclear engineering, chemistry, fluid dynamics, structural analysis and material research. It’s easy to see why these disciplines were quick to take up computational science.

Other disciplines, such as medicine (e.g. medical imaging, blood flow simulations, bone structure simulations), biology (e.g. ecosystem and environmental modelling) and economics are embracing computational science as well.
It has become quite common to come across terms like computational economics or computational biology.

Even more recently, advances in machine learning has led to an entirely new subfield of computational science and its application across a huge range of disciplines.
```

2025-01-28 21:15 UTC, alasdairwilson commented on high_performance_computing/computer_simulations/01_intro.md
> +If you want to know what sorts of applications are run on the UK’s national supercomputer ARCHER2, visit the relevant page on the ARCHER2 website. Is there anything that surprises you there?
```suggestion
:::callout{variant="discussion"}
If you want to know what sorts of applications are run on the UK’s national supercomputer ARCHER2, visit the relevant page on the ARCHER2 website. Is there anything that surprises you there?
:::
```

2025-01-28 21:16 UTC, alasdairwilson commented on high_performance_computing/computer_simulations/01_intro.md
> +
```suggestion
```

2025-01-30 13:25 UTC, alasdairwilson reviewed
Sorry for the mega-review, and for submitting it early by accident, but there you go anyway...

I am happy to leave reorganising the sections for a follow up PR, but I do think the HPC theme needs something done to keep it manageable.

2025-01-30 13:25 UTC, alasdairwilson commented on high_performance_computing/computer_simulations/02_weather_simulations.md
> +Another bottleneck is related to the observational data. The atmosphere is a chaotic system - without substantial amounts of data the chances of creating accurate forecasts decrease significantly, es
```suggestion
Another bottleneck is related to the observational data. The atmosphere is a chaotic system - without substantial amounts of data the chances of creating accurate forecasts decrease significantly, especially for increased forecast range. That is why the weather forecasting relies on the observational data coming from many different sources, both terrestrial and space based. It has to be noted that they describe the atmosphere in a slightly different way and so there is no unique way to represent the data uniformly, this makes calibrating and pre-processing the data to be used as input to the simulations an ongoing challenge.
Despite the difficulty of utilising these disparate data sources, it’s absolutely crucial to have as many different sources as possible, otherwise the forecasts will only be able to capture large scale patterns.
```

2025-01-30 13:25 UTC, alasdairwilson commented on high_performance_computing/computer_simulations/03_towards_future.md
> +
```suggestion
2022 saw the first exascale system, [https://www.top500.org/system/180047/](Frontier), based at Oak Ridge National Laboratory, with 2 more exascale systems, Aurora and El Capitan - both also in the US, following in 2024. Although at some level this is just an arbitrary number, it has become a significant technological (and political) milestone and more machines will follow in the near future as computing needs continue to grow.
```

2025-01-30 13:25 UTC, alasdairwilson commented on high_performance_computing/computer_simulations/03_towards_future.md
> +If we were to build a 1 Exaflop/s computer today, using standard Intel Xeon processors, then it would consume around 400 megawatts of power: that’s enough electricity for 700,000 households, or about
```suggestion
If we were to build a 1 Exaflop/s computer today, using standard Intel Xeon processors, then it would consume around 400 megawatts of power: that’s enough electricity for 700,000 households, or about 1% of the UK’s entire electricity generating capacity!
That’s not only hugely expensive, but it would require a big investment in engineering infrastructure, and would be politically challenging from a carbon footprint point of view.
There are also plans to use waste heat from supercomputers as heating for homes, or for direct energy recovery which could substantially decrease the cost and environmental impact of running these scales of machines.
```

2025-01-30 13:25 UTC, alasdairwilson commented on high_performance_computing/computer_simulations/03_towards_future.md
> +AI takes a rather different approach: rather than writing a separate program for each problem, you write software that can learn how to solve a much more general problem. This can be done by creating
```suggestion
AI takes a rather different approach: rather than writing a separate program for each problem, you write software that can learn how to solve a much more general problem. This can be done by creating an artificial neural network which takes an input (such as an image of a face) and produces an output (such as “that looks like David”).
We first train the network on a set of known results (e.g. a set of passport photos that have already been identified by a human), and then apply the trained network to the unknown input to get useful results (e.g. “this person is David because he looks like David’s passport photo”).
All neural networks work on this basic principle of pattern recognition whether it is recognising subjects in images, trends in data, or predicting the next word(s) in a sequence (LLMs).
This is called “Machine Learning”.
```

2025-01-30 13:25 UTC, alasdairwilson commented on high_performance_computing/computer_simulations/03_towards_future.md
> +Neural networks have been around for a long time, but recent advances in computer hardware have enabled them to be large enough and fast enough to begin to tackle problems that were previously imposs
```suggestion
Neural networks have been around for a long time, but only recent advances in computer hardware have enabled them to be large enough and fast enough to begin to tackle problems that were previously impossible to address. The combination of modern Machine Learning software and powerful computers has come to be called Deep Learning. It is also a very parallelisable problem: if I have to train my network on 1000 known images, each image can be processed independently on a separate CPU-core. We are starting to see people designing and building supercomputers specifically targeted at Deep Learning. GPUs, with their extreme parallel nature, are very well suited to machine learning problems, and Google has even designed its own “TPU” (Tensor Processing Unit) processor specifically targeted at Deep Learning problems.
```

2025-01-30 15:35 UTC, alasdairwilson commented
Apologies @steve-crouch for both the insane amount of suggestions and the fact I accidentally submitted the review part way (meaning some future comments got added as single comments rather than the review)

Anyway, done now 👍

2025-02-06 11:23 UTC, steve-crouch commented
Many thanks for the very comprehensive review, @alasdairwilson! The suggestions were excellent in simplifying and clarifying the text. I've reviewed and (I hope, given the scale of the review comments) accepted all changes. I've also fixed the content's textual references to the prior week-based schedule from the original content (#199) as you suggested.

2025-02-07 11:02 UTC, alasdairwilson requested changes
So there are 2 markdown lint errors:

These changes should fix them.

2025-02-07 11:10 UTC, alasdairwilson commented
> Many thanks for the very comprehensive review, @alasdairwilson! The suggestions were excellent in simplifying and clarifying the text. I've reviewed and (I hope, given the scale of the review comments) accepted all changes. I've also fixed the content's textual references to the prior week-based schedule from the original content (#199) as you suggested.

So there are actually like 190 more review comments or something you have to hit the load more to get 20 at a time (or go through the whole review on the changes tab but that's probably more of a pain).

that goes for both the reviews:

https://github.com/UNIVERSE-HPC/course-material/pull/187#pullrequestreview-2559334556

and


https://github.com/UNIVERSE-HPC/course-material/pull/187#pullrequestreview-2580622311

which has 9 or so.

If you are willing to accept them all then you can just "add them to batch" one at a time rather than commiting them directly and then commit when finished, which is a bit easier. I am not a maintainer on this repo sadly so can't take away the pain.

2025-02-12 09:15 UTC, steve-crouch commented
> So there are actually like 190 more review comments or something you have to hit the load more to get 20 at a time (or go through the whole review on the changes tab but that's probably more of a pain).
> ...
> If you are willing to accept them all then you can just "add them to batch" one at a time rather than commiting them directly and then commit when finished, which is a bit easier. I am not a maintainer on this repo sadly so can't take away the pain.

Yes, so once I realised how many there were I went through the remainder using the batch method (and then committing the collected batch), but it appears they weren't accepted. I'll go through the remainder again and batch the batch (?) submissions intro smaller groups and see if that works.

2025-02-13 13:02 UTC, steve-crouch commented on high_performance_computing/supercomputing/01_intro.md
> +© SURFsara
Yes good catch. I've been in touch with the original material developers, and it turns out this referred to image/text content that has subsequently been removed anyway so I've removed these.

2025-02-13 13:44 UTC, steve-crouch commented
I've gone through and hopefully approved all the suggestions now @alasdairwilson , but if I missed any or they didn't go through let me know. I've also added a new issue related to a question in your review:

- #215 - Consider replacements for end-episode MCQs in Foundational HPC material

2025-05-02 14:37 UTC, alasdairwilson approved these changes
Thanks @steve-crouch , there were still some comments but githubs interface is so garbage that I just grabbed the branch myself and fixed them up.

I think I have learned a valuable lesson here: that you can't leave 200+ comment reviews and expect github to work, maybe huge reviews need to be done as a patch instead or, as I've done here by pushes directly to fork then getting the author to look at the new diff.

Anyway, merging this now!

2025-05-02 14:37 UTC, merged